global:
  scrape_interval: 5s

scrape_configs:
  - job_name: flowgate-threshold
    static_configs:
      - targets: ["flowgate-threshold:9090"]

  - job_name: flowgate-buffered
    static_configs:
      - targets: ["flowgate-buffered:9090"]
